services:
  - name: crud
    type: web
    env: docker
    repo: https://github.com/Josh6335/crud.git  # Your actual GitHub repo
    branch: main
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-xxxxx.render.com  # Replace with actual Render DB host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: crud_e89m  # Your actual DB name from Render
      - key: DB_USERNAME
        value: crud_e89m_user  # Your actual DB username from Render
      - key: DB_PASSWORD
        value: YourDatabasePassword  # Your actual DB password from Render (keep it secret)

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan cache:clear
      php artisan config:clear

    startCommand: |
      php artisan migrate --force
      apache2-foreground  # Starts Apache instead of `php artisan serve`

databases:
  - name: laravel-db
    plan: free
    databaseName: crud_e89m
    user: crud_e89m_user
