services: 
  - name: crud
    type: web
    env: docker
    repo: https://github.com/Josh6335/crud.git  # Your actual GitHub repo
    branch: main
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase: laravel-db
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase: laravel-db
      - key: DB_USERNAME
        fromDatabase: laravel-db
      - key: DB_PASSWORD
        fromDatabase: laravel-db

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000

databases:
  - name: laravel-db
    plan: free
    databaseName: crud_e89m
    user: crud_e89m_user
